/*
 * generated by Xtext 2.10.0
 */
package org.osate.xtext.aadl2.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.osate.aadl2.ModelUnit

@RunWith(XtextRunner)
@InjectWith(Aadl2InjectorProvider)
class Aadl2ParsingTest{

	@Inject
	ParseHelper<ModelUnit> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
