/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ipl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IPLStandaloneSetup extends IPLStandaloneSetupGenerated {

	def static void doSetup() {
		new IPLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
