/*
 * generated by Xtext 2.10.0
 */
package org.osate.xtext.aadl2.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class Aadl2UiModule extends AbstractAadl2UiModule {
}
