/*
 * generated by Xtext 2.10.0
 */
package org.osate.xtext.aadl2.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class Aadl2ProposalProvider extends AbstractAadl2ProposalProvider {
}
