/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ipl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.example.ipl.iPL.Spec

@RunWith(XtextRunner)
@InjectWith(IPLInjectorProvider)
class IPLParsingTestExpr{

	@Inject
	ParseHelper<Spec> formulaParseHelper

	@Test 
	def void loadArithm() {
		val result = formulaParseHelper.parse('''
			1 + 2 = 3;
		''')
		Assert.assertTrue(result.imports.size == 0)
		Assert.assertTrue(result.decls.size == 0)
		Assert.assertTrue(result.formulas.size == 1)
		
	}

}
