/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ipl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.ipl.IPLRuntimeModule
import org.xtext.example.ipl.IPLStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class IPLIdeSetup extends IPLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new IPLRuntimeModule, new IPLIdeModule))
	}
	
}
